---
- name: Manage Services
  hosts: all
  become: true
  vars:
    services_to_manage:
      - name: nginx
        state: started  # Can be started, stopped, restarted
      - name: opensearch
        state: restarted
      - name: tomcat
        state: stopped
      - name: splunk
        state: started
      - name: wfc
        state: restarted

  tasks:
    - name: Manage Services (systemd)
      systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ services_to_manage }}"
      when: ansible_service_mgr == 'systemd'

    - name: Manage Services (service)
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ services_to_manage }}"
      when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart'

    - name: Check Service Status After Action (systemd)
      systemd:
        name: "{{ item.name }}"
      register: service_status_systemd
      loop: "{{ services_to_manage }}"
      when: ansible_service_mgr == 'systemd'

    - name: Check Service Status After Action (service)
      service:
        name: "{{ item.name }}"
      register: service_status_service
      loop: "{{ services_to_manage }}"
      when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart'

    - name: Report Service Status After Action (systemd)
      debug:
        msg: "{{ item.item.name }}: {{ item.status.ActiveState | default('unknown') }}"
      loop: "{{ service_status_systemd.results | default([]) }}"
      when: ansible_service_mgr == 'systemd' and service_status_systemd is defined

    - name: Report Service Status After Action (service)
      debug:
        msg: "{{ item.item.name }}: {{ item.status.Status | default('unknown') }}"
      loop: "{{ service_status_service.results | default([]) }}"
      when: (ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart') and service_status_service is defined